version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: yacy-search-server_web_1
      APP_PORT: 2801
  
  web:
    image: yacy/yacy_search_server:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: sh -c "chown -R 1000:1000 /opt/yacy_search_server/DATA"
    ports:
      - "2801:8090"
      - "8443:8443"
    volumes:
       - ${APP_DATA_DIR}/data/yacy/:/opt/yacy_search_server/DATA/

    environment:
      UID: "1000"
      GID: "1000"
