version: "3.7"

services:
  #app_proxy:
  #  environment:
  #    APP_HOST: yacy-search-server_web_1
  #    APP_PORT: 2798
  
  web:
    image: yacy/yacy_search_server:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "2799:8090"
      - "8443:8443"
    volumes:
       - ${APP_DATA_DIR}/data:/opt/yacy_search_server/DATA

    environment:
      - PUID=1000
      - PGID=1000
