version: "3.7"

volumes:
  yacy_data:
    driver: local
    driver_opts:
      type: none
      device: ${APP_DATA_DIR}/data
      o: bind

services:
  app_proxy:
    environment:
      APP_HOST: yacy-search-server_web_1
      APP_PORT: 2802
  
  web:
    image: aveygospam/yacy-search-server:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "2802:8090"
      - "8443:8443"
    volumes:
      - yacy_data:/app

    environment:
      YACY_DATA_PATH: /app/yacy/
