version: "3.7"

volumes:
  yacy_data:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind

services:
  app_proxy:
    environment:
      APP_HOST: yacy-search-server_web_1
      APP_PORT: 2802
  
  web:
    #image: aveygospam/yacy-search-server:latest
    image: yacy/yacy_search_server:latest
    #user: "1000:1000"
    restart: on-failure
    
    logging:
      options:
        max-size: "200m"
        max-file: "2"

    stop_grace_period: 1m
    ports:
      - "2802:8090"
    volumes:
      #- yacy_data:/opt/yacy_search_server/DATA
      - ${APP_DATA_DIR}/data:/opt/yacy_search_server/DATA
