version: "2.1"
services:
  app_proxy:
    environment:
      APP_HOST: ipfs_app_1
      APP_PORT: 80
  app:
    image: lscr.io/linuxserver/ipfs
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_DATA_DIR}/config:/config
    ports:
      - 2811:80
      - 2812:4001
      - 2813:5001
      - 2814:8080
      - 2815:443
    restart: unless-stopped